### PR TITLE
Added SquidPunch to core team! \o/

### PR DESCRIPTION
**Pull request by jamonholmgren**

### CODE REVIEW

**Comment by jamonholmgren** [comment]
We'll have to see what Travis says.

**Comment by squidpunch** [comment]
+1 for branch name.

**Comment by silasjmatson** [comment]
:+1:

**Comment by ryanlntn** [comment]
:tada: :smile: :tada:

**Comment by ajrobertson** [comment]
:+1:

**Comment by markrickert** [comment]
I know i'm late to the party, but :+1:!

**Comment by squidpunch** [comment]
thanks guys!

**Pull request merged**
