### PR TITLE
Don't use on_init within WebScreen

### LINKED ISSUE #598: PM::WebScreen should not use on_init to set up the screen
https://github.com/clearsightstudio/ProMotion/blob/master/lib/ProMotion/web/web_screen_module.rb#L13

This requires you to use super when using on_init in the app. This is not expected behavior.

### PR DESCRIPTION
**Pull request by ryanlntn**
Fixes #598. Also cleans up a bit of the setup logic.

### CODE REVIEW

**Comment by markrickert** [comment]
:+1:  Nice! I'm actually working with WebScreen right now, so i'll throw it in my project and let you know if i have any problems.

**Comment by ryanlntn** [comment]
Awesome! :smile:

**Comment by jamonholmgren** [comment]
:+1: Looks good. Will merge into `master` and release another point release when Travis is done.

**Comment by markrickert** [comment]
Everything looks ok on my end... looks like the travis failure is unrelated.

**Comment by jamonholmgren** [comment]
Travis is sucking hard these days. These failures don't happen on my Mac.

**Pull request merged**
