### PR TITLE
Version 2.3 Megalopullus request

### PR DESCRIPTION
**Pull request by jamonholmgren**
Includes:

* PR #618 Allow search bar to be hidden initially
* PR #606 Adds capability for table_footer_view
* PR #602 Add image inset support for tab bar item
* PR #595 Feature/support module
* PR #582 Allow setting of multiple nav bar buttons instead of just one left an one right
* PR #581 Adds on_tab_selected
* PR #579 implemented nav_bar_button class method RE #272
* PR #565 Adds header_will_display method to PM::TableScreen
* PR #663 Adds `on_load` back to cell dequeue code
* PR #641 Custom search for PM::TableScreen
* PR #658 Fix cell height issue

Will write a proper changelog soon.

### CODE REVIEW

**Comment by kevinvangelder** [comment]
Documented #618.

**Comment by silasjmatson** [comment]
Documented #606.

**Comment by silasjmatson** [comment]
Documented Checklist

* [X] PR #618 Allow search bar to be hidden initially
* [X] PR #606 Adds capability for table_footer_view
* [ ] PR #602 Add image inset support for tab bar item
* [ ] PR #595 Feature/support module
* [ ] PR #582 Allow setting of multiple nav bar buttons instead of just one left an one right
* [ ] PR #581 Adds on_tab_selected
* [ ] PR #579 implemented nav_bar_button class method RE #272
* [ ] PR #565 Adds header_will_display method to PM::TableScreen

**Comment by silasjmatson** [comment]
@jamonholmgren The added features are now all documented.

**Comment by jamonholmgren** [comment]
@silasjmatson @kevinvangelder Thanks guys!

**Comment by kevinvangelder** [comment]
@jamonholmgren Updated docs per additional requests.

**Comment by jamonholmgren** [comment]
I think we're very close. However, I'd like to get all the outstanding bugs resolved (or as many as possible) before we merge this in. Maybe we can merge and launch Monday or Tuesday.

**Comment by jamonholmgren** [comment]
We are merged! I'll leave the version-2.3 branch alive for a while.

**Pull request merged**
