### PR TITLE
Fix wrong cell detection problem in search_result_table of longpressable TableScreen.

### PR DESCRIPTION
**Pull request by satoyos**
...e TableScreen.

### CODE REVIEW

**Comment by satoyos** [comment]
Sorry, I'll rewrite my comment.

In [my Sample App](https://github.com/satoyos/PM_Longpress), I found a problem; 
1. Launch TableScreen App.
2. Search.
3. Scroll up search result,
4. and Long-press a cell.
5. Then, wrong cell is detected...

I think, `searchResultsTableView` should be used, instead of `table_view`, to detect `gesture_point` and `index_path`.
Is that right?

**Comment by jamonholmgren** [comment]
Good catch, @satoyos ! @markrickert , look good to you?

**Comment by markrickert** [comment]
Yup! looks good! Another good catch!

**Comment by jamonholmgren** [comment]
Thanks @satoyos !

**Comment by satoyos** [comment]
My pleasure!
I'm looking forward to next update!

**Pull request merged**
