### PR TITLE
Move call to setNavigationBarHidden to view_will_appear

### LINKED ISSUE #700: How to navigate back to home screen without nav bar?
I'm running into an issue with transitioning from one screen to another then back to the first screen. I need to create a home screen which does not have a nav bar (splash page with signup/login button). I can't seem to figure out the code I need to create the behavior I'm trying to achieve. Here's what I have so far (working with RedPotion):

```ruby
class AppDelegate < PM::Delegate
  status_bar true, animation: :fade
  def on_load(app, options)
    open HomeScreen.new(nav_bar: false)
  end
end

class HomeScreen < PM::Screen
  stylesheet HomeScreenStylesheet

  def on_load
    append(UIButton, :sign_up_button).on(:tap) do
      open CreateAccountScreen.new(nav_bar: true), animated: true
    end
    append(UILabel, :sign_in_text)
  end
end

class CreateAccountScreen < PM::Screen
  title "Create Account"
  stylesheet CreateAccountScreenStylesheet

  def on_load
    set_nav_bar_button :left, title: '<', action: :nav_left_button
    @hello_world = append!(UILabel, :hello_world)
  end

  def nav_left_button
    open_root_screen HomeScreen.new(nav_bar: false), animated: true
    # I've also tried
    # open HomeScreen
    # open HomeScreen.new(nav_bar: false), animated: true
    # close
  end
end
```

When I tap the "sign up" button, it does not slide in (just immediately displays). When I tap the back button (left nav button) it crashes the app with an error:

> Terminating app due to uncaught exception 'ArgumentError', reason: 'create_account_screen.rb:17:in `nav_left_button': wrong number of arguments (2 for 1) (ArgumentError)

What am I doing wrong?

### PR DESCRIPTION
**Pull request by ryanlntn**
This fixes #700.

### CODE REVIEW

**Comment by ryanlntn** [comment]
API question @jamonholmgren . Should you be able to call `open MyScreen, hide_nav_bar: true` or only `open MyScreen.new(hide_nav_bar: true)`? I ask because `set_up_screen_for_open` in `ScreenNavigation` doesn’t call `screen_init` which is where I put the definition of `@screen_options`. So my specs are failing now but the fix works and provides for more general deferred evaluation.

**Comment by jamonholmgren** [comment]
You should be able to do the `open MyScreen, hide_nav_bar: true`. Actually, we'll be moving that direction with PM Android, since Android doesn't support opening instances of screens (you can only give it a class).

**Comment by ryanlntn** [comment]
@jamonholmgren Now that you mention it I seem to remember having this conversation with you a couple months ago. 

Updated! Travis should pass soon.

**Comment by markrickert** [comment]
Is this ready to merge?

**Comment by jamonholmgren** [comment]
:shipit:

**Pull request merged**
