### PR TITLE
Allow setting of multiple nav bar buttons instead of just one left an one right

### PR DESCRIPTION
**Pull request by markrickert**
```ruby
set_nav_bar_buttons :right, [{
  custom_view: my_custom_view_button
},{
  title: "Tasks",
  image: UIImage.imageNamed("whatever"),
  action: nil
}]

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@markrickert Sorry, just saw your question!

I think it's fine as-is. Will merge at next minor update.

**Comment by ryanlntn** [comment]
Staged for release on the [version-2.3](https://github.com/clearsightstudio/ProMotion/tree/version-2.3) branch.

**Comment by anguskwan** [comment]
it's cool!

**Comment by markrickert** [comment]
Documented - https://github.com/clearsightstudio/ProMotion/wiki/API-Reference:-ProMotion::Screen#set_nav_bar_buttonsside-button_array

**Comment by jamonholmgren** [comment]
@markrickert , just FYI, we're moving to ReadTheDocs and including documentation in the pull request (`./docs` folder) in future pull requests.

**Comment by jamonholmgren** [comment]
@kevinvangelder  Can you include Mark's documentation for this PR in the #622 PR?

**Pull request closed without merging**
