### PR TITLE
Add image inset support for tab bar item

### PR DESCRIPTION
**Pull request by ryanlntn**
@jamonholmgren I was considering doing the `:properties` hash thing but this is one of the last tab bar item properties left for us to implement. This way feels more consistent with what we already have.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Maybe a spec?

**Comment by ryanlntn** [comment]
Surely. :grin:

**Comment by jamonholmgren** [comment]
shirley

**Comment by ryanlntn** [comment]
That spec totally passes locally. Promise.

**Comment by jamonholmgren** [comment]
:+1: Stage on 2.3 branch.

**Comment by ryanlntn** [comment]
Staged for release on the [version-2.3](https://github.com/clearsightstudio/ProMotion/tree/version-2.3) branch.

**Pull request closed without merging**
