### PR TITLE
Feature/will display cell

### PR DESCRIPTION
**Pull request by creationrose**
This will be a helpful hook for infinite scroll applications.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
:+1: 

@silasjmatson @ryanlntn @markrickert @squidpunch ?

**Comment by ryanlntn** [comment]
Cool :+1:

**Comment by squidpunch** [comment]
:+1: 

I think I just saw a comment on another issue or PR from you @jamonholmgren saying we needed this - and I was going to whip it up, but @creationrose beat me too it!

**Comment by jamonholmgren** [comment]
I'll merge when travis passes.

**Comment by jamonholmgren** [comment]
Thanks @creationrose ! I think first female contributor to ProMotion? :-)

**Comment by creationrose** [comment]
Yay. Trying to make history and be awesome...

**Pull request merged**
